import cv2
import numpy as np
import matplotlib.pyplot as plt
image = cv2.imread('lena.jpeg', cv2.IMREAD_GRAYSCALE)
hist_original, bins_original = np.histogram(image.flatten(), 256, [0, 256])
min_val = np.min(image)
max_val = np.max(image)
stretched_image = np.uint8(255 * ((image - min_val) / (max_val - min_val)))
hist_stretched, bins_stretched = np.histogram(stretched_image.flatten(), 256, [0, 256])
plt.figure(figsize=(10, 8))
plt.subplot(2, 2, 1)
plt.imshow(image, cmap='gray')
plt.title('Original Image')
plt.axis('off')
plt.subplot(2, 2, 2)
plt.imshow(stretched_image, cmap='gray')
plt.title('Contrast Stretched Image')
plt.axis('off')
plt.subplot(2, 2, 3)
plt.plot(hist_original, color='black')
plt.title('Original Image Histogram')
plt.xlabel('Pixel Intensity')
plt.ylabel('Frequency')
plt.subplot(2, 2, 4)
plt.plot(hist_stretched, color='black')
plt.title('Stretched Image Histogram')
plt.xlabel('Pixel Intensity')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()
