import cv2
import numpy as np
import matplotlib.pyplot as plt
input_image = cv2.imread("lena.jpeg", 0)
input_hist = cv2.calcHist([input_image], [0], None, [256], [0, 256])
output_image = cv2.equalizeHist(input_image)
output_hist = cv2.calcHist([output_image], [0], None, [256], [0, 256])
plt.figure(figsize=(10, 6))
plt.subplot(2, 2, 1)
plt.bar(np.arange(256), input_hist.flatten(), color='blue')
plt.title("Input Histogram")
plt.xlabel("Pixel Value")
plt.ylabel("Frequency")
plt.subplot(2, 2, 2)
plt.bar(np.arange(256), output_hist.flatten(), color='green')
plt.title("Output Histogram")
plt.xlabel("Pixel Value")
plt.ylabel("Frequency")
plt.subplot(2, 2, 3)
plt.imshow(input_image, cmap='gray')
plt.title("Input Image")
plt.axis('off')
plt.subplot(2, 2, 4)
plt.imshow(output_image, cmap='gray')
plt.title("Output Image")
plt.axis('off')
plt.tight_layout()
plt.show()
